---
title: "Re-analysis of SRP029880"
author: "Shannon E. Ellis"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{recount quick start guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r vignetteSetup, echo=FALSE, message=FALSE, warning = FALSE}
## Track time spent on making the vignette
startTime <- Sys.time()
```

```{r load-packages, message = FALSE, warning = FALSE}
library(recount)
library(edgeR)
library(reshape)

## load colors
  bright= c(red=rgb(222,45,38, maxColorValue=255), #de2d26
            pink=rgb( 255, 102, 153, maxColorValue=255), #ff6699
            orange=rgb(232,121,12, maxColorValue=255),   #e8790c
            yellow=rgb(255,222,13, maxColorValue=255), #ffde0d          
            green=rgb(12,189,24, maxColorValue=255),  #0cbd18           
            teal=rgb(59,196,199, maxColorValue=255), #3bc4c7
            blue=rgb(58,158,234, maxColorValue=255), #3a9eea
            purple=rgb(148,12,232, maxColorValue=255)) #940ce8 
```

# Load predicted phenotypes

```{r load-predictions, message = FALSE, warning = FALSE}
## load predicted phenotypes
load('/dcl01/leek/data/sellis/barcoding/output/PredictedPhenotypes_v0.0.04.rda')
df = PredictedPhenotypes #70479
df$predicted_sex <- as.factor(tolower(df$predicted_sex))

```


# Load SRA reported metadata

```{r load-meatdata, message = FALSE, warning = FALSE}

## load SRA metadata
load('/dcl01/leek/data/recount-website/metadata/metadata_sra.Rdata')
metadata <- metadata[!is.na(metadata$bigwig_path), ]
sra_meta = metadata
rm(metadata)
pd = read_csv("https://raw.githubusercontent.com/nellore/runs/master/sra/v2/hg38/SraRunInfo.csv")
sra_meta = left_join(as.data.frame(sra_meta),pd,by=c("run"="Run","sample"="Sample"))
colnames(sra_meta)[4] <- "sample_id"

## combine metadata and predicted phentypes
meta = left_join(sra_meta,df)
```


# Identify a study of interest

```{r id-study, message = FALSE, warning = FALSE}

## Looking for a paired end sequencing study
## predicted_samplesource == tissue
## where sex was not reported
## N >=20 

## but first, let's get studies where cancer is mentioned in the reported metadata
df <- meta[grep("cancer", meta$characteristics),]
## now let's be sure to include all samples from these studies (in case the controls don't have the word cancer in 'characteristics')
projects = unique(df$project)
df <- meta[meta$project %in% projects,]

## now: let's filter on criteria of interest
 (possible_projects <- df %>%  dplyr::filter(predicted_sequencingstrategy=="PAIRED", is.na(reported_sex), predicted_samplesource=="tissue") %>% group_by(project) %>% summarise(Count = n()) %>% dplyr::filter(Count>=20)) 

 ## checking out total sample size
 N=c()
 for(i in 1:nrow(possible_projects)){
  a <- print(meta[meta$project==possible_projects$project[i],] %>% nrow())
  N = c(N,a)
}

## if samples meeting criteria and total study sample size are not the same
## means that some samples within study do not meet above critera
## will filter out these studies to only include studies in which all samples meet above criteria
possible_projects <- cbind(possible_projects,N)

(possible_projects = possible_projects %>% dplyr::filter(Count==N))

## let's look at sex breakdown in each study
for(i in 1:nrow(possible_projects)){
  print(meta[meta$project==possible_projects$project[i],"predicted_sex"] %>% table())
}
```

# Extract SRP029880 metadata

```{r study-meatdata, message = FALSE, warning = FALSE}

md <- meta[meta$project==possible_projects$project[2],]

```

# Download SRP029880 from recount2

```{r study-data, message = FALSE, warning = FALSE}
#get RSE for this project
project="SRP029880"

## Download the gene-level RangedSummarizedExperiment data
if(!file.exists(file.path(project, 'rse_gene.Rdata'))) {
	download_study(project)
}

## Load the data
load(file.path(project, 'rse_gene.Rdata'))

## Browse the project at SRA
browse_study(project)

## ensure metadata and covmat are in the same order
identical(colData(rse_gene)$run,md$sample_id)

## Extract the sample characteristics
geochar <- lapply(split(colData(rse_gene), seq_len(nrow(colData(rse_gene)))), geo_characteristics)

## as an aside, predicted_tissue doing pretty well here....
table(md$predicted_tissue)
## all colon tissue were predicted to be small intestine or colon. Metastases were either SI or liver
```
# Organize data and sample info

```{r organize-data, message = FALSE, warning = FALSE}
## Get sample information in order
## dx
dx = colData(rse_gene)$title
dx[grep("primary",dx)] <- "PC"
dx[grep("metastasized",dx)] <- "MC"
dx[grep("normal",dx)] <- "NC"

## sampleID 
sampleID = colData(rse_gene)$title
sampleID <- gsub("primary colorectal cancer AMC_","s",sampleID)
sampleID <- gsub("normal colon AMC_","s",sampleID)
sampleID <- gsub("metastasized cancer AMC_","s",sampleID)
sampleID <-gsub("-1","",sampleID)
sampleID <-gsub("-2","",sampleID)
sampleID <-gsub("-3","",sampleID)

## We can now define some sample information to use
sample_info <- data.frame(
    run = colData(rse_gene)$run,
    group = dx,
    sampleID = as.factor(sampleID), 
    sex = md$predicted_sex,
    tissue = as.factor(md$predicted_tissue)
)
sample_info$sex <- droplevels(sample_info$sex)
sample_info$tissue <- droplevels(sample_info$tissue)

## get everything in order
tissue = as.character(sample_info$tissue)
## group small intestine and colon samples together
tissue[tissue!="liver"] <- "intestine"
sample_info$tissue = as.factor(tissue)

## are all samples predicted to have hte same sex?
sample_info %>% group_by(sampleID,sex) %>% summarise(Count=n())
# one is off (s22) -- predicted male twice and female once

## Scale counts by taking into account the total coverage per sample
rse <- scale_counts(rse_gene)

## Add sample information for DE analysis
colData(rse)$group <- sample_info$group
colData(rse)$sampleID <- sample_info$sampleID

## Run DGE (as in the publication)
group <- as.factor(sample_info$group)
levels(group)<-levels(group)[c(3,2,1)]
## log2 counts data
counts <- assays(rse)$counts
counts <- log2(counts+1)

## break down into groups used for analysis
counts_NC_PC <- counts[,sample_info$group=="NC" | sample_info$group=="PC"]
counts_MC_PC <- counts[,sample_info$group=="MC"| sample_info$group=="PC"]

sample_info_NC_PC <- sample_info[sample_info$group=="NC" | sample_info$group=="PC",]
sample_info_MC_PC <- sample_info[sample_info$group=="MC" | sample_info$group=="PC",]
```

# Run DGEA (as in Kim et al.)

```{r DGEA-Kim, message = FALSE, warning = FALSE}
## Run DGE (as in the publication)
## DGE no covariates
## NC:PC
y_NC_PC <- DGEList(counts=counts_NC_PC,group=sample_info_NC_PC$group)
y_NC_PC <- calcNormFactors(y_NC_PC)
design <- model.matrix(~sample_info_NC_PC$group)
y_NC_PC2 <- estimateDisp(y_NC_PC,design)
#To perform likelihood ratio tests:
fit_NC_PC <- glmFit(y_NC_PC2,design)
lrt_NC_PC <- glmLRT(fit_NC_PC,coef=2)
topTags(lrt_NC_PC)

## MC:PC
y_MC_PC <- DGEList(counts=counts_MC_PC,group=sample_info_MC_PC$group)
y_MC_PC <- calcNormFactors(y_MC_PC)
design <- model.matrix(~sample_info_MC_PC$group)
y_MC_PC2 <- estimateDisp(y_MC_PC,design)
#To perform likelihood ratio tests:
fit_MC_PC <- glmFit(y_MC_PC2,design)
lrt_MC_PC <- glmLRT(fit_MC_PC,coef=2)
topTags(lrt_MC_PC)
```


# Run DGEA (~ sex)

```{r DGEA-sex, message = FALSE, warning = FALSE}
## add sex into analysis
##NC:PC
design <- model.matrix(~sample_info_NC_PC$group+sample_info_NC_PC$sex)
y_NC_PC_sex <- estimateDisp(y_NC_PC,design)
#To perform likelihood ratio tests:
fit_NC_PC_sex <- glmFit(y_NC_PC_sex,design)
lrt_NC_PC_sex <- glmLRT(fit_NC_PC_sex,coef=2)
topTags(lrt_NC_PC_sex)

## MC:PC
design <- model.matrix(~sample_info_MC_PC$group+sample_info_MC_PC$sex)
y_MC_PC_sex <- estimateDisp(y_MC_PC,design)
#To perform likelihood ratio tests:
fit_MC_PC_sex <- glmFit(y_MC_PC_sex,design)
lrt_MC_PC_sex <- glmLRT(fit_MC_PC_sex,coef=2)
topTags(lrt_MC_PC_sex)

```

# Run DGEA (~ sex + tissue)

```{r DGEA-sex-tissue, message = FALSE, warning = FALSE}

## MC:PC
design <- model.matrix(~sample_info_MC_PC$group+sample_info_MC_PC$sex+sample_info_MC_PC$tissue)
y_MC_PC_sex_tissue <- estimateDisp(y_MC_PC,design)
#To perform likelihood ratio tests:
fit_MC_PC_sex_tissue <- glmFit(y_MC_PC_sex_tissue,design)
lrt_MC_PC_sex_tissue <- glmLRT(fit_MC_PC_sex_tissue,coef=2)
topTags(lrt_MC_PC_sex_tissue)
```
# Extract Significant Genes

```{r sig-genes, message = FALSE, warning = FALSE}
## Get significant genes (as in Kim et al.)
## significance as defined in paper
## logFC>2, pval<0.001
## add column genes for rownames

## Kim et al. analysis
j=nrow(counts)
NC_PC <- topTags(lrt_NC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001, abs(logFC)>=2)
topTags(lrt_NC_PC,j)$table %>% dim
# topTags(lrt_NC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001) %>% dim()
# topTags(lrt_NC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(abs(logFC)>=2) %>% dim()
dim(NC_PC)

MC_PC <- topTags(lrt_MC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001, abs(logFC)>=2)
topTags(lrt_MC_PC,j)$table %>% dim
# topTags(lrt_MC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001) %>% dim()
# topTags(lrt_MC_PC,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(abs(logFC)>=2) %>% dim()
dim(MC_PC)

## ~sex analysis
NC_PC_sex <- topTags(lrt_NC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001, abs(logFC)>=2)
topTags(lrt_NC_PC_sex,j)$table %>% dim
# topTags(lrt_NC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001) %>% dim()
# topTags(lrt_NC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(abs(logFC)>=2) %>% dim()
dim(NC_PC_sex)

MC_PC_sex <- topTags(lrt_MC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001, abs(logFC)>=2)
topTags(lrt_MC_PC_sex,j)$table %>% dim
# topTags(lrt_MC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001) %>% dim()
# topTags(lrt_MC_PC_sex,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(abs(logFC)>=2) %>% dim()
dim(MC_PC_sex)

## ~ sex + tissue analysis
MC_PC_sex_tissue <- topTags(lrt_MC_PC_sex_tissue,j)$table %>% do(mutate(.,gene=rownames(.))) %>% dplyr::filter(PValue<0.001, abs(logFC)>=2)

## sort p-values
NC_PC_p <- NC_PC %>% arrange(PValue)
NC_PC_sex_p <- NC_PC_sex %>% arrange(PValue)
#NC_PC_sex_tissue_p <- NC_PC_sex_tissue %>% arrange(PValue)

MC_PC_p <- MC_PC %>% arrange(PValue)
MC_PC_sex_p <- MC_PC_sex %>% arrange(PValue)
MC_PC_sex_tissue_p <- MC_PC_sex_tissue %>% arrange(PValue)

## overlap for genes between studies : sex
table(NC_PC_p$gene %in% NC_PC_sex_p$gene)
table(NC_PC_sex_p$gene %in% NC_PC_p$gene)

table(MC_PC_p$gene %in% MC_PC_sex_p$gene)
table(MC_PC_sex_p$gene %in% MC_PC_p$gene)

## overlap for genes between studies : sex + tissue
#table(NC_PC_p$gene %in% NC_PC_sex_tissue_p$gene)
#table(NC_PC_sex_tissue_p$gene %in% NC_PC_p$gene)
table(MC_PC_p$gene %in% MC_PC_sex_tissue_p$gene)
table(MC_PC_sex_tissue_p$gene %in% MC_PC_p$gene)
```

# Assess concordance

```{r concordance, message = FALSE, warning = FALSE, width=8, height=8}

## calculate concordance : sex
conc_NC_PC_sex <- NULL
for(i in 1:length(NC_PC_p$PValue)){
    conc_NC_PC_sex[i] <- sum(NC_PC_sex_p$gene[1:i] %in% NC_PC_p$gene[1:i])
}

conc_MC_PC_sex <- NULL
for(i in 1:length(MC_PC_p$PValue)){
    conc_MC_PC_sex[i] <- sum(MC_PC_sex_p$gene[1:i] %in% MC_PC_p$gene[1:i])
}

a<- c(nrow(NC_PC),nrow(MC_PC),nrow(NC_PC_sex),nrow(MC_PC_sex)) %>% max

pdf("plots/Conc_sex.pdf",family="Roboto Condensed",height=10, width=10)
par(mgp=c(4.5,2,0),mar = c(7, 7.5, 4.1, 2.1),mfrow = c(1, 1), font.lab = 1.8, cex.lab = 3, font.axis = 1.6, cex.axis = 2, cex.main=3.5)
plot(seq(1:a), conc_NC_PC_sex[1:a], 
     type = 'l', las = 0,
     xlim = c(0, a),
     ylim = c(0, a),
     xlab = 'ordered genes: no covariates',
     ylab = 'ordered genes: with covariates',
     main = 'Concordance: ~ sex')
for(k in 1:round((a/100),0)){
    abline(v = k * 100, cex = 0.5, col = 'lightgrey')
    abline(h = k * 100, cex = 0.5, col = 'lightgrey')
}
abline(coef=c(0,1),col="grey48")
lines(seq(1:a), conc_NC_PC_sex[1:a], col = bright["blue"], lwd = 5)
lines(seq(1:a), conc_MC_PC_sex[1:a], col = bright["red"], lwd = 5)
legend(0, 315, legend=c("NC:PC","MC:PC"), col=c(bright["blue"],bright["red"]),lty=1,lwd=5,bg="white", cex=2.5)
dev.off()

conc_MC_PC_sex_tissue<- NULL
for(i in 1:length(MC_PC_p$PValue)){
    conc_MC_PC_sex_tissue[i] <- sum(MC_PC_sex_tissue_p$gene[1:i] %in% MC_PC_p$gene[1:i])
}

a<- c(nrow(NC_PC),nrow(MC_PC),nrow(MC_PC_sex_tissue)) %>% max

pdf("plots/Conc_sex_tissue.pdf",family="Roboto Condensed",height=10, width=10)
par(mgp=c(4.5,2,0),mar = c(7, 7.5, 4.1, 2.1),mfrow = c(1, 1), font.lab = 1.8, cex.lab = 3, font.axis = 1.6, cex.axis = 2, cex.main=3.5)
plot(seq(1:a), conc_MC_PC_sex_tissue[1:a], 
     type = 'l', las = 0,
     xlim = c(0, a),
     ylim = c(0, a),
     xlab = 'ordered genes: no covariates',
     ylab = 'ordered genes: with covariates',
     main = 'Concordance: ~ sex + tissue')
for(k in 1:round((a/100),0)){
    abline(v = k * 100, cex = 0.5, col = 'lightgrey')
    abline(h = k * 100, cex = 0.5, col = 'lightgrey')
}
abline(coef=c(0,1),col="grey48")
#lines(seq(1:a), conc_NC_PC_sex_tissue[1:a], col = bright["blue"], lwd = 3)
lines(seq(1:a), conc_MC_PC_sex_tissue[1:a], col = bright["red"], lwd = 5)
legend(0, 315, legend=c("MC:PC"), col=c(bright["red"]),lty=1,lwd=5,bg="white", cex=1.6)
dev.off()

## summarize number of DGE identified
counts_kim <- c(2861,1846) #from publication
counts_our <- c(nrow(NC_PC),nrow(MC_PC))
counts_sex <- c(nrow(NC_PC_sex), nrow(MC_PC_sex))
counts_sex_tissue <- c(NA, nrow(MC_PC_sex_tissue))


sumdf <- rbind(counts_kim, counts_our,counts_sex,counts_sex_tissue)
colnames(sumdf) <- c("NC:PC","MC:PC")
rownames(sumdf) <- c("Kim et al.","no covariates","~ sex","~ sex + tissue")
# barplot(sumdf,beside=T, col=bright[c(5,2,6,4)],ylab="No. genes", main="Significantly differentially exprssed genes by analysis")

sumdf <- melt(sumdf)
colnames(sumdf) <- c("analysis", "comparison","genes")

ggplot(data = sumdf, aes(x=comparison, y = genes,label = genes)) + 
  labs(y="No. of Genes",x="Comparison",title="Significantly differentially expressed genes by analysis") +
    geom_bar(stat="identity", aes(fill = analysis),position="dodge") +
    geom_text(aes(fill=analysis),size = 12, position = position_dodge(width = 0.9),colour="black") +
    scale_fill_manual(values=c("#0CBD18","#FF6699","#3BC4C7","#FFDE0D"))+
    theme_bw()+
    theme(legend.title=element_blank(),legend.text=element_text(size=30),plot.title = element_text(hjust = 0.5),text = element_text(size=22), panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))

pdf("plots/DGEA.pdf",family="Roboto Condensed",height=5, width=16)
ggplot(data = sumdf, aes(x=comparison, y = genes,label = genes)) + 
  labs(y="No. of Genes",x="Comparison",title="Significantly differentially expressed genes by analysis") +
    geom_bar(stat="identity", aes(fill = analysis),position="dodge") +
    geom_text(aes(fill=analysis),size = 10, position = position_dodge(width = 0.9),colour="black") +
    scale_fill_manual(values=c("#0CBD18","#FF6699","#3BC4C7","#FFDE0D"))+
    theme_bw()+
    theme(legend.title=element_blank(),legend.text=element_text(size=30),plot.title = element_text(hjust = 0.5),text = element_text(size=30), panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))
dev.off()


```


# Vignette information

```{r reproducibility}
## Time spent creating this report:
diff(c(startTime, Sys.time()))

## Date this report was generated
message(Sys.time())

## Reproducibility info
options(width = 120)
devtools::session_info()
```

Code for creating the vignette

```{r createVignette, eval=FALSE}
## Create the vignette
library('rmarkdown')
system.time(render('/dcl01/leek/data/sellis/barcoding/phenopredict_usecase/dgea_analysis.Rmd', 'BiocStyle::html_document'))

## Extract the R code
library('knitr')
knit('/dcl01/leek/data/sellis/barcoding/phenopredict_usecase/dgea_analysis.Rmd', tangle = TRUE)
```
